import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { initialState,decay,apply,socialEffect,projectRelationships,selectAttention,agendaEligible,expression,chooseSocial } from './index.ts';
import { neutralAppraisal,type Appraisal,type EvidenceInput } from '../../contracts/src/domain.ts';
const identity=randomUUID();
const praise:Appraisal={...neutralAppraisal,target:'character',act:'praise',strength:3,uncertain:false};
describe('core-rules-v1',()=>{
 it('D01 holds four seconds then halves in45s',()=>{const s=apply(initialState(0),{eventId:randomUUID(),targetId:null,now:0,stimuli:{joy:.18}});expect(decay(s,4000).affect.joy.value).toBe(.18);expect(decay(s,49000).affect.joy.value).toBeCloseTo(.09,8);});
 it('D02 praise applies .18,.09,.03,0 without extending hold',()=>{const history:EvidenceInput[]=[];let state=initialState(0);const amounts=[];for(let i=0;i<4;i++){const effect=socialEffect(praise,history,identity,0);amounts.push(effect.stimulus);history.push({id:randomUUID(),identityId:identity,kind:'praise',at:0,order:BigInt(i),strength:3,appliedStimulus:effect.stimulus});state=apply(state,{eventId:randomUUID(),targetId:identity,now:0,stimuli:{joy:effect.stimulus},holdEligible:i===0});}expect(amounts).toEqual([.18,.09,.02999999999999997,0]);expect(state.affect.joy.holdUntil).toBe(4000);});
 it('F10 sliding window consumes historical applied stimuli',()=>{const history:EvidenceInput[]=[];const values=[];for(const at of [0,300000,601000,602000]){const effect=socialEffect(praise,history,identity,at);values.push(effect.stimulus);history.push({id:randomUUID(),identityId:identity,kind:'praise',at,order:BigInt(history.length),strength:3,appliedStimulus:effect.stimulus});}expect(values).toEqual([.18,.09,.09,.06]);});
 it('D04 quoted hostile and uncertain inputs have zero social effects',()=>{expect(socialEffect({...praise,target:'quoted',hostility:3,act:'criticism'},[],identity,0).stimulus).toBe(0);expect(socialEffect({...praise,uncertain:true},[],identity,0).stimulus).toBe(0);});
 it('D05 wrong answer leaves mood .57 with both emotions',()=>{const s=apply(initialState(0),{eventId:randomUUID(),targetId:'problem',now:0,stimuli:{frustration:.2,embarrassment:.2}});expect(s.mood.pleasantness).toBeCloseTo(.57);expect(s.affect.frustration.value).toBe(.2);expect(s.affect.embarrassment.value).toBe(.2);});
 it('D17 time stepping leaves same emotion and mood',()=>{const s=apply(initialState(0),{eventId:randomUUID(),targetId:null,now:0,stimuli:{joy:.3,frustration:.2}});let small=s,large=s;for(let t=1000;t<=100000;t+=1000)small=decay(small,t);for(let t=10000;t<=100000;t+=10000)large=decay(large,t);expect(small.affect.joy.value).toBeCloseTo(large.affect.joy.value,8);expect(small.mood.pleasantness).toBeCloseTo(large.mood.pleasantness,8);});
 it('D18 mood returns to baseline half-distance in900s, time never reverses',()=>{const s=initialState(100);s.mood.pleasantness=.7;expect(decay(s,900100).mood.pleasantness).toBeCloseTo(.65);expect(decay(s,0).mood.asOf).toBe(100);});
 it('D06 Seoul day and independent help limits',()=>{const now=Date.parse('2026-10-03T14:59:00Z');const inputs:EvidenceInput[]=[{id:randomUUID(),identityId:identity,kind:'first_observed',at:now,order:1n},{id:randomUUID(),identityId:identity,kind:'first_observed',at:now+120000,order:2n}];for(let i=0;i<4;i++)inputs.push({id:randomUUID(),identityId:identity,kind:'verified_hint',problemId:`p${i}`,at:now,order:BigInt(i+3)});const r=projectRelationships(inputs).get(identity)!;expect(r.familiarity).toBeCloseTo(.06);expect(r.affinity).toBeCloseTo(.53);expect(r.verifiedProblemCount).toBe(4);expect(r.interactionDays).toBe(2);});
 it('F03 fairness applies only within highest priority, expiration exact20s',()=>{const other=randomUUID();const candidates=[{id:'a',identityId:identity,receivedAt:100,priority:1 as const},{id:'b',identityId:other,receivedAt:90,priority:0 as const}];expect(selectAttention(candidates,200,identity,2)?.id).toBe('a');candidates[1].priority=1;expect(selectAttention(candidates,200,identity,2)?.id).toBe('b');expect(selectAttention(candidates,20100,identity,2)).toBeNull();});
 it('D12 30second8second gate plus participant and attempt budget',()=>{const base={now:30000,sessionStart:0,lastUser:22000,lastOutput:0,busy:false,participantPresent:true,expiresAt:90000,attempted:false,createdSessionId:'old',sessionId:'new'};expect(agendaEligible(base)).toBe(true);expect(agendaEligible({...base,now:29999})).toBe(false);expect(agendaEligible({...base,attempted:true})).toBe(false);expect(agendaEligible({...base,participantPresent:false})).toBe(false);});
 it('F09 expression hysteresis and listening override',()=>{const s=initialState(0);s.affect.joy.value=.2;s.expression={kind:'happy',since:0};s.affect.embarrassment.value=.5;expect(expression(s,1000).kind).toBe('happy');expect(expression(s,2000).kind).toBe('embarrassed');s.turn.listening=true;expect(expression(s,2000).kind).toBe('listening');});
});

it('F05 unselected semantic acts listen while uncertain questions clarify once',()=>{const state=initialState(0);for(const act of ['other','help_offer','teasing','hint'] as const){const a={...neutralAppraisal,target:'character' as const,act,uncertain:false};expect(chooseSocial(state,a,socialEffect(a,[],identity,0),identity,0).action).toBe('listen');}const q={...neutralAppraisal,act:'question' as const};expect(chooseSocial(state,q,socialEffect(q,[],identity,0),identity,0).purpose).toBe('clarify');});
