import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,clientId,Wire,type Packet} from './wire.ts';
import './style.css';
const CHARACTER_ID='10000000-0000-4000-8000-000000000001';
const isStage=location.pathname==='/stage';
function App(){const[token,setToken]=useState(sessionStorage.getItem('accessToken'));const[error,setError]=useState(''),[code,setCode]=useState('');
  async function pair(value:string){try{const result=await api('/api/auth/exchange','POST',{code:value.trim(),clientInstanceId:clientId()});if(result.role!==(isStage?'stage':'studio'))throw new Error('이 화면의 페어링 코드가 아니야');sessionStorage.setItem('accessToken',result.accessToken);setToken(result.accessToken);setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));const incoming=params.get('pair');if(incoming){history.replaceState(null,'',location.pathname);void pair(incoming);}},[]);
  if(!token)return <main className="pair"><p className="eyebrow">로컬 캐릭터 작업실</p><h1>{isStage?'Stage 연결':'작업실 연결'}</h1><p>{isStage?'작업실에서 발급한 Stage 코드를 입력해 주세요.':'실행 터미널에 표시된 일회용 코드를 입력해 주세요.'}</p><form onSubmit={e=>{e.preventDefault();void pair(code);}}><label htmlFor="pair-code">일회용 연결 코드</label><input id="pair-code" value={code} onChange={e=>setCode(e.target.value)} autoComplete="off"/><button>연결</button></form><p role="alert">{error}</p></main>;
  return <><button className="repair-connection secondary" onClick={()=>{sessionStorage.removeItem('accessToken');setToken(null);setError('');}}>다시 연결</button>{isStage?<Stage onError={setError} error={error}/>:<Studio onError={setError} error={error}/>}</>;
}
function Studio({onError,error}:{onError:(s:string)=>void;error:string}) {
  const[session,setSession]=useState<any>(null),[state,setState]=useState<any>(null),[status,setStatus]=useState('연결 중'),[ready,setReady]=useState<any>({}),[identities,setIdentities]=useState<any[]>([]),[identity,setIdentity]=useState(''),[text,setText]=useState(''),[timeline,setTimeline]=useState<any[]>([]),[memories,setMemories]=useState<any[]>([]),[problems,setProblems]=useState<any[]>([]),[stages,setStages]=useState<any[]>([]),[agendas,setAgendas]=useState<any[]>([]),[activeResponse,setActiveResponse]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const [recoverStage,setRecoverStage]=useState<string|null>(null),[previousClosed,setPreviousClosed]=useState(false);
  async function selectStage(stageId:string,confirmed=false){try{await api(`/api/sessions/${session.id}/output-owner`,'POST',{stageClientId:stageId,previousStageClosed:confirmed});setRecoverStage(null);setPreviousClosed(false);onError('');await refresh();}catch(e){if((e as Error).message==='previous_output_unconfirmed'){setRecoverStage(stageId);setPreviousClosed(false);}onError((e as Error).message);}}
  const pendingChat=useRef<{id:string;text:string}|null>(null);const[pendingStatus,setPendingStatus]=useState('');
  const wire=useRef<Wire|null>(null),sessionRef=useRef<any>(null);sessionRef.current=session;
  async function act(fn:()=>Promise<unknown>){setBusy(true);onError('');try{await fn();await refresh();}catch(e){onError((e as Error).message);}finally{setBusy(false);}}
  async function refresh(){const s=await api('/api/sessions/current');setSession(s);if(s?.id!==wire.current?.sessionId&&wire.current?.connectionId)wire.current.subscribe(s?.id??null);
    const [r,m,p,ids,ss,aa]=await Promise.all([api('/health/ready'),api(`/api/characters/${CHARACTER_ID}/memories`),api('/api/problems'),api('/api/identities'),api('/api/stages'),api(`/api/characters/${CHARACTER_ID}/agendas`)]);setReady(r);setMemories(m);setProblems(p);setIdentities(ids);setStages(ss);setAgendas(aa);setIdentity(x=>x||ids[0]?.id||'');if(s)setTimeline(await api(`/api/sessions/${s.id}/timeline`));}
  useEffect(()=>{const channel=new Wire(packet=>{if(packet.type==='connection.welcome'){channel.subscribe(packet.payload.activeSessionId);void refresh().catch(e=>onError(e.message));}if(packet.type==='state.snapshot'){setState(packet.payload);setActiveResponse(packet.payload.activeResponse?.id??null);}if(packet.type==='runtime.status')onError(packet.payload.code);if(packet.type==='command.result'){if(packet.payload.status==='rejected')onError(packet.payload.error.code);if(pendingChat.current?.id===packet.payload.requestId){const pending=pendingChat.current!;if(packet.payload.status!=='rejected')setText(value=>value===pending.text?'':value);setBusy(false);setPendingStatus(packet.payload.status==='rejected'?'입력 거부: 내용을 확인해 다시 보내세요.':'저장됨');pendingChat.current=null;}}if(packet.type==='connection.lost'){setBusy(false);if(pendingChat.current)setPendingStatus('연결이 끊겼어요. 입력 결과를 확인하세요.');}if(packet.type==='session.ended'){setSession(null);setActiveResponse(null);}},setStatus);wire.current=channel;channel.connect();const poll=setInterval(()=>{void refresh().catch(e=>onError(e.message));},2000);return()=>{clearInterval(poll);channel.close();};},[]);
  const activity=state?.activity;
  return <div className="shell"><header><div><p className="eyebrow">같이 겪은 일이 이어지는 곳</p><h1>캐릭터 작업실</h1></div><div className="toolbar"><span>{status}</span><button disabled={busy} onClick={()=>void act(async()=>{if(session){await api(`/api/sessions/${session.id}/stop`,'POST',{reason:'operator_stop'});}else{await api('/api/sessions','POST',{sessionId:crypto.randomUUID(),characterId:CHARACTER_ID,configVersion:'1'});}})}>{session?'만남 종료':'새 만남 시작'}</button></div></header>
    <div className="readiness"><strong>{ready.database==='ready'?'저장 준비됨':'저장 확인 중'}</strong><span>사건 해석(Jev): {ready.appraisal?.provider==='jev-mock'?'검증용 모의 응답':ready.appraisal?.status==='ready'?'추론 확인됨':ready.appraisal?.status==='blocked'?'API 사용 차단됨':ready.appraisal?.status==='configured'?'설정됨 · 추론 미검증':'사용 불가'}</span><span>대사 생성(Qwen): {ready.llm==='synthetic_test_only'?'검증용 합성 fixture':ready.llm==='ready'?'준비됨':'실제 추론 미검증'}</span><span>음성: {ready.tts==='synthetic_probe_verified_voice_preset_missing'?'합성 목소리 파일 검증됨 · 사용자 목소리 미선택':'참조 목소리와 자원 검증 필요'}</span><span>전사: {ready.stt==='probe_verified_production_disabled'?'파일 검증됨 · 마이크 단계 비활성':'준비 필요'}</span></div>
    {error&&<p className="error" role="alert">{error}</p>}
    <main className="workspace"><section className="conversation"><h2>이번 만남</h2><p className="subtle">{session?'등록된 상대의 입력을 받고, 관측과 반응을 확인해요.':'새 만남을 시작하면 입력과 활동을 연결할 수 있어요.'}</p>
      <form onSubmit={e=>{e.preventDefault();try{const id=crypto.randomUUID();pendingChat.current={id,text};setBusy(true);setPendingStatus('저장 결과 확인 중');wire.current!.send('chat.submit',{identityId:identity,text},id);setTimeout(()=>{if(pendingChat.current?.id===id){setBusy(false);setPendingStatus('아직 결과가 없어요. 입력 결과를 확인하세요.');}},5000);}catch(err){setBusy(false);onError((err as Error).message);}}}><label htmlFor="identity">대화 상대</label><select id="identity" value={identity} onChange={e=>setIdentity(e.target.value)}>{identities.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select><label htmlFor="message">할 말</label><textarea id="message" value={text} onChange={e=>setText(e.target.value)} maxLength={1000} placeholder="안녕. 오늘은 어떤 문제를 볼까?" disabled={!session}/><button disabled={!session||busy||!text.trim()}>입력 보내기</button></form><p role="status" className="subtle">{pendingStatus}</p>{pendingChat.current&&<button className="secondary" onClick={()=>void act(async()=>{const result=await api('/api/commands/'+pendingChat.current!.id);if(result){setPendingStatus('저장이 확인됐어요.');setText('');pendingChat.current=null;}else setPendingStatus('저장된 입력이 없어요. 내용을 유지했어요.');})}>입력 결과 확인</button>}
      <h2>퍼즐</h2>{activity?<div className="activity"><p>{activity.public_prompt}</p><p className="subtle">{activity.status} · 힌트 {activity.hints_used}/1 · 제출 {activity.auto_attempts_used}/{activity.auto_attempts_granted}</p><div className="toolbar"><button disabled={busy||activity.hints_used>=1} onClick={()=>void act(()=>api(`/api/activities/${activity.id}/hints`,'POST',{hintId:problems.find(p=>p.problem_id===activity.problem_id)?.hint_ids[0],identityId:identity}))}>등록 힌트 사용</button><button className="secondary" disabled={busy} onClick={()=>void act(()=>api(`/api/activities/${activity.id}/retry`,'POST',{}))}>한 번 더 시도</button><button className="secondary" disabled={busy} onClick={()=>void act(()=>api(`/api/activities/${activity.id}/resume`,'POST',{}))}>이어 풀기</button><button className="secondary" disabled={busy} onClick={()=>void act(()=>api(`/api/activities/${activity.id}/end`,'POST',{}))}>문제 종료</button></div></div>:<div className="problem-list">{problems.map(p=><div key={p.problem_id}><p>{p.public_prompt}</p><button className="secondary" disabled={!session||busy} onClick={()=>void act(()=>api(`/api/sessions/${session.id}/activities`,'POST',{problemId:p.problem_id}))}>이 문제 시작</button></div>)}</div>}
      {agendas.filter(a=>a.status==='offered').map(a=><div className="agenda" key={a.id}><strong>이어서 할까요?</strong><p>실제로 전달된 퍼즐 재개 제안이에요.</p><button onClick={()=>void act(()=>api(`/api/sessions/${session.id}/agenda-answer`,'POST',{accept:true}))}>이어가기</button><button className="secondary" onClick={()=>void act(()=>api(`/api/sessions/${session.id}/agenda-answer`,'POST',{accept:false}))}>이번엔 쉬기</button></div>)}
      <h2>출력 화면</h2><button className="secondary" onClick={()=>void act(async()=>{const pairing=await api('/api/stage-pairings','POST',{});window.open(`/stage#pair=${pairing.code}`,'_blank','noopener');})}>Stage 열기</button><ul className="stage-list">{stages.map(stage=><li key={stage.clientId}><span>{stage.owner?'현재 출력 화면':stage.ready?'준비된 Stage':'준비 중'}</span><button className="secondary" disabled={!session||!stage.ready||stage.owner} onClick={()=>void act(()=>selectStage(stage.clientId))}>출력 선택</button></li>)}</ul>{recoverStage&&<div className="activity" role="alert"><p>이전 Stage의 출력 중지를 확인하지 못했어요. 이전 Stage 창을 직접 닫은 뒤 확인해 주세요.</p><label><input type="checkbox" checked={previousClosed} onChange={e=>setPreviousClosed(e.target.checked)}/>이전 Stage 창을 직접 닫았습니다</label><button className="secondary" disabled={busy||!previousClosed||!session} onClick={()=>void act(()=>selectStage(recoverStage,true))}>닫힘 확인 후 출력 선택</button></div>}
    </section><aside className="inspection"><h2>캐릭터 상태</h2>{state?.activeResponse&&<div className="activity"><strong>현재 행동: {state.activeResponse.plan?.action}</strong><p>{state.activeResponse.plan?.purpose}</p><small>기억 근거: {state.activeResponse.plan?.memoryIds?.join(', ')||'없음'}</small><button className="secondary" onClick={()=>{if(activeResponse)wire.current?.send('response.stop',{responseId:activeResponse,reason:'operator_stop'},crypto.randomUUID());}}>응답 중지</button></div>}{state?<><p className="subtle">관측 상태 #{state.stateVersion} · 표현 {state.state.expression.kind}</p><dl className="affect">{Object.entries(state.state.affect).map(([key,value]:[string,any])=><div key={key}><dt>{{joy:'기쁨',frustration:'답답함',surprise:'놀람',embarrassment:'당황'}[key]}</dt><dd>{value.value.toFixed(2)}<meter min="0" max="1" value={value.value}/></dd></div>)}</dl><p>기분 {state.state.mood.pleasantness.toFixed(2)}</p><h3>상대별 경험</h3>{state.relationships.length?<table><thead><tr><th>상대</th><th>친숙함</th><th>호감</th><th>도움</th></tr></thead><tbody>{state.relationships.map((r:any)=><tr key={r.identity_id}><td>{r.display_name}</td><td>{r.familiarity.toFixed(2)}</td><td>{r.affinity.toFixed(2)}</td><td>{r.verified_problem_count}문제</td></tr>)}</tbody></table>:<p className="subtle">아직 관측한 관계 근거가 없어요.</p>}</>:<p className="subtle">연결 후 저장된 상태를 표시해요.</p>}
      <h2>남겨 둔 기억</h2>{memories.length?memories.map(m=><article className="memory" key={m.id}><p>{m.content}</p><small>{m.kind} · 버전 {m.content_version}</small><div className="toolbar"><button className="secondary" onClick={()=>void act(async()=>{const content=window.prompt('문구 정정 (관측 사실은 유지)',m.content);if(content)await api(`/api/memories/${m.id}/corrections`,'POST',{expectedVersion:m.content_version,content,sourceEventIds:m.source_event_ids});})}>문구 정정</button><button className="secondary" onClick={()=>void act(()=>api(`/api/memories/${m.id}`,'DELETE',undefined,{'If-Match':`"${m.content_version}"`}))}>기억 삭제</button></div></article>):<p className="subtle">확인된 활동 경험이 생기면 여기에 남아요.</p>}
      <h2>관측과 선택</h2><ol className="timeline">{timeline.map(e=><li key={e.id}><strong>{e.kind}</strong><span>{e.attention_status}</span>{e.payload?.text&&<p>{e.payload.text}</p>}<small>{e.id}</small>{e.data_status==='active'&&e.kind==='chat.final'&&<button className="secondary" onClick={()=>void act(()=>api(`/api/events/${e.id}`,'DELETE',undefined,{'If-Match':`"${e.revision}"`}))}>원본 삭제</button>}</li>)}</ol>
    </aside></main></div>;
}
function Stage({onError,error}:{onError:(s:string)=>void;error:string}) {
  const[caption,setCaption]=useState(''),[status,setStatus]=useState('연결 중'),[expression,setExpression]=useState('neutral');
  const wire=useRef<Wire|null>(null),epoch=useRef('0'),generation=useRef('0'),owner=useRef(false),cancelled=useRef(new Set<string>()),queue=useRef<any[]>([]),running=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),playbackVersion=useRef(0),activeSegment=useRef<any>(null);
  function stopPlayback(){playbackVersion.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;running.current=false;activeSegment.current=null;setCaption('');}
  function clear(){owner.current=false;queue.current=[];stopPlayback();}
  function syncGeneration(value:string){if(BigInt(value)<=BigInt(generation.current))return;generation.current=value;queue.current=queue.current.filter(s=>BigInt(s.generationEpoch)>=BigInt(value));if(activeSegment.current&&BigInt(activeSegment.current.generationEpoch)<BigInt(value))stopPlayback();void renderNext();}
  async function renderNext(){if(running.current||!owner.current)return;const segment=queue.current.shift();if(!segment)return;if(cancelled.current.has(segment.responseId)||segment.outputEpoch!==epoch.current||segment.generationEpoch!==generation.current)return void renderNext();running.current=true;setCaption(segment.text);
    activeSegment.current=segment;const version=++playbackVersion.current;
    await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));if(version!==playbackVersion.current)return;
    if(!owner.current||cancelled.current.has(segment.responseId)||segment.outputEpoch!==epoch.current||segment.generationEpoch!==generation.current){stopPlayback();void renderNext();return;}
    const report={responseId:segment.responseId,segmentId:segment.segmentId,generationEpoch:segment.generationEpoch,outputEpoch:segment.outputEpoch};wire.current?.send('caption.shown',report,crypto.randomUUID());const duration=Math.max(2000,Math.min(8000,[...segment.text].length/15*1000));timer.current=setTimeout(()=>{if(version!==playbackVersion.current)return;if(owner.current&&!cancelled.current.has(segment.responseId))wire.current?.send('caption.finished',report,crypto.randomUUID());stopPlayback();void renderNext();},duration);
  }
  useEffect(()=>{const channel=new Wire(packet=>{const p=packet.payload;if(packet.type==='connection.welcome'){clear();channel.subscribe(p.activeSessionId);if(p.activeSessionId)channel.send('stage.ready',{audioUnlocked:false,avatarReady:false,supportsExpressions:['neutral','listening','happy','embarrassed','uncomfortable']});}
    if(packet.type==='expression.set')setExpression(p.expression);
    if(packet.type==='session.snapshot')syncGeneration(p.generationEpoch);
    if(packet.type==='output.granted'){clear();owner.current=true;epoch.current=p.outputEpoch;generation.current=p.generationEpoch;setStatus('자막 출력 중');}
    if(packet.type==='speech.segment'&&owner.current&&!cancelled.current.has(p.responseId)){queue.current.push(p);void renderNext();}
    if(packet.type==='response.cancel'){cancelled.current.add(p.responseId);queue.current=queue.current.filter(s=>s.responseId!==p.responseId);if(activeSegment.current?.responseId===p.responseId)stopPlayback();if(p.newGenerationEpoch)syncGeneration(p.newGenerationEpoch);void renderNext();}
    if(packet.type==='output.revoke'){clear();channel.send('output.released',{outputEpoch:p.outputEpoch,stopRequestId:p.stopRequestId},crypto.randomUUID());setStatus('출력 해제됨');}
    if(['connection.lost','session.ended'].includes(packet.type)){clear();setStatus('출력 대기');}
    if(packet.type==='command.result'&&p.status==='rejected')onError(p.error.code);
  },setStatus);wire.current=channel;channel.connect();const poll=setInterval(()=>{void api('/api/sessions/current').then(s=>{if(s&&channel.connectionId&&s.id!==channel.sessionId){clear();channel.subscribe(s.id);channel.send('stage.ready',{audioUnlocked:false,avatarReady:false,supportsExpressions:['neutral','listening','happy','embarrassed','uncomfortable']});}}).catch(()=>{});},2000);return()=>{clearInterval(poll);clear();channel.close();};},[]);
  return <main className={`stage expression-${expression}`}><p className="stage-status">{status} · 자막 Stage</p>{error&&<p role="alert" className="error">{error}</p>}<div className="expression-label">{{neutral:'차분히 기다리는 중',listening:'듣는 중',happy:'기쁜 반응',embarrassed:'잠깐 당황한 반응',uncomfortable:'조금 불편한 반응'}[expression]}</div><p className="caption" aria-live="polite">{caption}</p><p className="stage-note">음성과 아바타는 실제 자원 검증 후 연결돼요.</p></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
