// Reviewed SQL migrations carry CHECK/composite FK definitions. Drizzle maps the
// queried columns; sql migrations remain the deployment contract, never schema push.
import { pgTable, uuid, text, bigint, jsonb, timestamp, integer, doublePrecision } from 'drizzle-orm/pg-core';
const stamp = (name:string) => timestamp(name,{withTimezone:true,mode:'date'}).notNull();
export const characters=pgTable('characters',{id:uuid('id').primaryKey(),displayName:text('display_name').notNull()});
export const characterState=pgTable('character_state',{characterId:uuid('character_id').primaryKey(),version:bigint('version',{mode:'bigint'}).notNull(),configVersion:bigint('config_version',{mode:'bigint'}).notNull(),generationEpoch:bigint('generation_epoch',{mode:'bigint'}).notNull(),schemaVersion:integer('schema_version').notNull(),snapshotAt:stamp('snapshot_at'),body:jsonb('body').notNull()});
export const events=pgTable('events',{id:uuid('id').primaryKey(),characterId:uuid('character_id').notNull(),sessionId:uuid('session_id').notNull(),identityId:uuid('identity_id'),kind:text('kind').notNull(),revision:bigint('revision',{mode:'bigint'}).notNull(),dataStatus:text('data_status').notNull(),attentionStatus:text('attention_status').notNull(),receivedAt:stamp('received_at'),payload:jsonb('payload')});
export const relationships=pgTable('relationships',{characterId:uuid('character_id').notNull(),identityId:uuid('identity_id').notNull(),familiarity:doublePrecision('familiarity').notNull(),affinity:doublePrecision('affinity').notNull(),interactionDays:integer('interaction_days').notNull(),verifiedProblemCount:integer('verified_problem_count').notNull(),verifiedHelpDays:integer('verified_help_days').notNull()});
export const memories=pgTable('memories',{id:uuid('id').primaryKey(),characterId:uuid('character_id').notNull(),sessionId:uuid('session_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),contentVersion:bigint('content_version',{mode:'bigint'}).notNull(),content:text('content'),facts:jsonb('facts'),occurredAt:stamp('occurred_at')});
