import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {OllamaProvider,validateDialogue,type TokenCounter} from './ollama.ts';
const counter:TokenCounter={count:async()=>10,countText:async()=>10};
it('AI01 exact structured enums and current event source enforced',async()=>{const id=randomUUID();const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async()=>new Response(JSON.stringify({done:true,message:{content:JSON.stringify({target:'character',act:'praise',strength:3,hostility:0,goal_relation:'unrelated',uncertain:false,evidence_refs:[randomUUID()]})}})));await expect(provider.appraise({id,text:'합성',identityId:randomUUID()},{})).rejects.toMatchObject({code:'invalid_output'});});
it('AI08 cloud/remote endpoint and model rejected',()=>{expect(()=>new OllamaProvider('qwen2.5:7b',counter,'http://example.com')).toThrow();expect(()=>new OllamaProvider('qwen2.5:7b-cloud',counter)).toThrow();});
it('AI13 token budget blocks provider invocation',async()=>{let invoked=false;const provider=new OllamaProvider('qwen2.5:7b',{count:async()=>3329,countText:async()=>0},undefined,async()=>{invoked=true;throw new Error();});await expect(provider.appraise({id:randomUUID(),text:'합성',identityId:randomUUID()},{})).rejects.toMatchObject({code:'input_too_long'});expect(invoked).toBe(false);});
it('AI03 streaming requires completion and ignores thinking',async()=>{const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async()=>new Response('{"message":{"content":"안녕.","thinking":"개인 분석"},"done":false}\n'));await expect(provider.dialogue({action:'answer',purpose:'question',targetIdentityId:null,expression:'neutral',maxSentences:2,delivery:'normal',memoryIds:[]},{})).rejects.toMatchObject({code:'invalid_output'});});
it('AI03 empty or oversized dialogue fails without mid-sentence cut',()=>{expect(()=>validateDialogue('',2)).toThrow();expect(()=>validateDialogue('가'.repeat(121),2)).toThrow();expect(validateDialogue('같이 풀어보자.',2)).toEqual(['같이 풀어보자.']);});
it('AI01 malformed structured JSON and uncertain semantic judgement without source reject',async()=>{for(const content of ['not-json',JSON.stringify({target:'character',act:'praise',strength:3,hostility:0,goal_relation:'unrelated',uncertain:true,evidence_refs:[]})]){const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async()=>new Response(JSON.stringify({done:true,message:{content}})));await expect(provider.appraise({id:randomUUID(),text:'합성',identityId:randomUUID()},{})).rejects.toMatchObject({code:'invalid_output'});}});
it('AI03 nonstring stream content rejected',async()=>{const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async()=>new Response('{"message":{"content":{"text":"가짜"}},"done":true}\n'));await expect(provider.dialogue({action:'answer',purpose:'question',targetIdentityId:null,expression:'neutral',maxSentences:2,delivery:'normal',memoryIds:[]},{})).rejects.toMatchObject({code:'invalid_output'});});

it('AI12 deadline rejects logically but serialized physical request remains occupied until done',async()=>{let calls=0,release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async(_url,options)=>{calls++;if(calls===1)await gate;const body=JSON.parse(options!.body as string),id=JSON.parse(body.messages[1].content).event.id;return new Response(JSON.stringify({done:true,message:{content:JSON.stringify({target:'character',act:'greeting',strength:0,hostility:0,goal_relation:'unrelated',uncertain:false,evidence_refs:[id]})}}),{headers:{'content-type':'application/json'}});},{deadlinesMs:{appraise:10,dialogue:10,solve:10}});const first=provider.appraise({id:randomUUID(),identityId:randomUUID(),text:'합성'},{ });await expect(first).rejects.toMatchObject({code:'provider_timeout'});const second=provider.appraise({id:randomUUID(),identityId:randomUUID(),text:'합성'},{});await new Promise(resolve=>setTimeout(resolve,5));expect(calls).toBe(1);await expect(provider.unloadOwnedModel()).rejects.toMatchObject({code:'physical_call_unconfirmed'});release();expect((await second).act).toBe('greeting');expect(calls).toBe(2);});
it('AI12 unconfirmed transport failure fences later model calls rather than release GPU ownership',async()=>{let calls=0;const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async()=>{calls++;throw new Error('synthetic transport lost');});await expect(provider.appraise({id:randomUUID(),identityId:randomUUID(),text:'합성'},{})).rejects.toMatchObject({code:'provider_unavailable'});await expect(provider.appraise({id:randomUUID(),identityId:randomUUID(),text:'합성'},{})).rejects.toMatchObject({code:'physical_call_unconfirmed'});expect(calls).toBe(1);});

it('AI01 appraisal-v2 supplies conversation roles without coercing quoted target',async()=>{const id=randomUUID(),identityId=randomUUID();let body:any;const provider=new OllamaProvider('qwen2.5:7b',counter,undefined,async(_url,options)=>{body=JSON.parse(options!.body as string);return new Response(JSON.stringify({done:true,message:{content:JSON.stringify({target:'quoted',act:'praise',strength:3,hostility:0,goal_relation:'unrelated',uncertain:false,evidence_refs:[id]})}}),{headers:{'content-type':'application/json'}});});const result=await provider.appraise({id,identityId,text:'그 사람은 "네 풀이가 정말 좋았어"라고 말했어.'},{});expect(result.target).toBe('quoted');expect(provider.appraisalPromptVersion).toBe('appraisal-v2');expect(JSON.parse(body.messages[1].content).conversation).toEqual({speaker:'user',speakerIdentityId:identityId,addressee:'character'});expect(body.messages[0].content).toContain('quoted=인용된 말');});
